INSERT INTO categories (name) VALUES ('Nintendo');
INSERT INTO categories (name) VALUES ('PC');
INSERT INTO categories (name) VALUES ('PlayStation');
INSERT INTO categories (name) VALUES ('Xbox');


INSERT INTO users (fullName, user, email, password, perfil, birthDay, image) VALUES ('Marcia', 'Marcia', '7a.mares7@gmail.com', '$2a$10$CAz7n.g8Q1FOYd1V6iW35uN02C1/aBfqM.2ZZPhE8H3hNuYtsEzxK', 'Admin', '1983-12-10', 'tlou2-dh.png');
INSERT INTO users (fullName, user, email, password, perfil, birthDay, image) VALUES ('Tomas', 'Fernandez', 'tomasfernandez@hotmail.com', '$2a$10$o9Vj5.2G.jha1w5KnD7a3u4CZoydzTPQHSbmD2kXBJMfn1ASyBvN.', 'Admin', '2002-07-07', 'asadsas.png');
INSERT INTO users (fullName, user, email, password, perfil, birthDay, image) VALUES ('juani', 'juanix', 'juani@mail.com', '$2a$10$Pv9L6kW0hZgo8ukNZfgDoeVLQZsTE18pP0.ANWgnMTFDOEk.1s9b2', 'Admin', '2004-03-09', 'defaultUser.png');
INSERT INTO users (fullName, user, email, password, perfil, birthDay, image) VALUES ('Franco', 'francoseccaspina', 'francosec2002@hotmail.com', '$2a$10$P7jigIpx5ldnufq/huiH1OrXtBJE3RiMlAfGVi/LZxEnmT/O5634K', 'User', '2022-09-14', 'defaultUser.png');


INSERT INTO products (name, description, price, categoryId, inOffer, image) VALUES ('The Last of us II', 'The Last of Us Part II es un videojuego de terror y de acción y aventuras de 2020 desarrollado por Naughty Dog y publicado por Sony Interactive Entertainment para PlayStation 4.1​ Ambientado cinco años después de The Last of Us (2013), el juego se centra en dos personajes jugables en un Estados Unidos post-apocalíptico cuyas vidas se entrelazan: Ellie, que busca venganza después de sufrir una tragedia, y Abby, una soldado que se ve envuelta en un conflicto entre su milicia y un culto religioso. El juego se juega desde la perspectiva de la tercera persona y le permite al jugador luchar contra enemigos humanos y criaturas caníbales parecidas a zombis con armas de fuego, armas improvisadas y sigilo.', 1500, 3, 1, 'tlou2-dh.png');
INSERT INTO products (name, description, price, categoryId, inOffer, image) VALUES ('FIFIA 22', 'FIFA 22 es un videojuego desarrollado por EA Vancouver y EA Romania, siendo publicado por EA Sports. Está disponible para PlayStation 4, PlayStation 5, Xbox Series X/S, Xbox One, Microsoft Windows, Google Stadia y Nintendo Switch. Es la vigésimo novena entrega en la serie FIFA y fue lanzado el 1 de octubre de manera global. El primer tráiler del juego fue presentado el 11 de julio de 2021 y muestra la nueva tecnología Hypermotion, que según palabras de EA brindará nueva experiencia más realista. Estas innovaciones están disponibles únicamente para PlayStation 5, Xbox Series y Stadia. Kylian Mbappé será el rostro de la portada por segunda vez consecutiva . A diferencia de juegos anteriores que poseían diferentes ediciones con más contenido, FIFA 22 sólo contará con dos ediciones: Ultimate y estándar. La edición Ultimate otorga al usuario de acceso anticipado al juego, junto con beneficios extras que no están disponibles en la edición estándar, con un respectivo valor de 60 o 70 dólares (edición estándar) y 100 dólares (edición Ultimate).', 1100, 1, 0, 'fifa-dh.png');
INSERT INTO products (name, description, price, categoryId, inOffer, image) VALUES ('Red dead II', 'Red Dead Redemption 2, estilizado Red Dead Redemption II, es un videojuego de acción-aventura western basado en el drama, en un mundo abierto y en perspectiva de primera y tercera persona, ​ con componentes para un jugador y multijugador.​ Fue desarrollado por Rockstar Games.', 1700, 4, 1, 'red2-dh.png');
INSERT INTO products (name, description, price, categoryId, inOffer, image) VALUES ('Grand Theft Auto', 'Grand Theft Auto', 1500, 2, 1, 'gtav-dh.png');
INSERT INTO products (name, description, price, categoryId, inOffer, image) VALUES ('Flight Simulator', 'Microsoft: Flight Simulator', 1600, 2, 1, 'flightSimulator.jpg');

